### SIGN UP
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "Nok-Nok",
    "password": "123456"
}

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Nok-Nok",
    "password": "123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "w",
    "password": "w"
}

###Search recipe by ingredients
GET http://localhost:3000/recipe/searchByIngredient
Content-Type: application/json

{
    "ingredients": ["apple","butter","ice cream"]
}

###POST/ADD a favorite recipe
POST http://localhost:3000/favoriteRecipe
Content-Type: application/json

{
    "id": 1,
    "title":"Apple Pie",
    "image": "ADSFGSFG",
    "sourceURL": "apple-pie-recipe.bing"
}

###GET/ACCESS the list of favorite recipes
GET http://localhost:3000/favoriteRecipe

###DELETE a favorite recipe
DELETE http://localhost:3000/favoriteRecipe?id=63f12e1e585c11b39a8da462
